# Descomposición de Cholesky

In [52]:
import numpy as np
#Para matrices (A) simétricas y definidas positivas,
#podemos hallar una matriz triangular (L) tal que A=L*Lt 


In [53]:
A=[[1.,2.,3.],[2.,8.,4.],[3.,4.,11.]]

In [54]:
print (A)

[[1.0, 2.0, 3.0], [2.0, 8.0, 4.0], [3.0, 4.0, 11.0]]


In [55]:
At=np.transpose(A)

In [56]:
print (At)

[[  1.   2.   3.]
 [  2.   8.   4.]
 [  3.   4.  11.]]


In [57]:
A==At

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [73]:
np.linalg.det(A)>0

True

In [59]:
L=np.linalg.cholesky(A)

In [60]:
print (L)

[[ 1.  0.  0.]
 [ 2.  2.  0.]
 [ 3. -1.  1.]]


In [61]:
Lt=np.transpose(L)

In [62]:
print (Lt)

[[ 1.  2.  3.]
 [ 0.  2. -1.]
 [ 0.  0.  1.]]


In [63]:
M=np.dot(L,Lt)

In [64]:
print (M)

[[  1.   2.   3.]
 [  2.   8.   4.]
 [  3.   4.  11.]]


In [66]:
A==M

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [67]:
B=[[0.,-2,4],[2.,0.,2.],[-4.,-2.,0.]]

In [68]:
print (B)

[[0.0, -2, 4], [2.0, 0.0, 2.0], [-4.0, -2.0, 0.0]]


In [70]:
k=np.linalg.cholesky(B)
# B es una matriz antisimétrica, determinante igual a 0

LinAlgError: Matrix is not positive definite

In [71]:
C=[[3,-2,-5,4],[-5,2,8,-5],[-2,4,7,-3],[2,-3,-5,8]]

In [74]:
print (np.linalg.det(C))

-54.0


In [75]:
L=np.linalg.cholesky(C)

LinAlgError: Matrix is not positive definite

In [76]:
P=[[2,1,1],[0,5,-2],[1,-3,4]]

In [77]:
Pt=np.transpose(P)

In [78]:
P==Pt

array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True]], dtype=bool)

In [79]:
print (np.linalg.det(P))

21.0


In [80]:
g=np.linalg.cholesky(P)

In [82]:
print (g)

[[ 1.41421356  0.          0.        ]
 [ 0.          2.23606798  0.        ]
 [ 0.70710678 -1.34164079  1.30384048]]
