# matrices

In [71]:
from numpy import *
a = matrix ([[1,-1,0],[0,1,0],[2,0,1]])
print (a)

[[ 1 -1  0]
 [ 0  1  0]
 [ 2  0  1]]


In [72]:
a.T #transpuesta


matrix([[ 1,  0,  2],
        [-1,  1,  0],
        [ 0,  0,  1]])

In [73]:
a.H # transpuesta conjugada 

matrix([[ 1,  0,  2],
        [-1,  1,  0],
        [ 0,  0,  1]])

In [74]:
b = a.I #inversa
print (b)

[[ 1.  1.  0.]
 [ 0.  1.  0.]
 [-2. -2.  1.]]


In [75]:
c = a*b producto de matrices
print (c)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [76]:
linalg.det(a) #determinante

1.0

In [77]:
d = matrix ([[1],[4],[7]]) #vector columna
print (d)

[[1]
 [4]
 [7]]


In [78]:
e = linalg.solve(a,d) #sistema de ecuaciones
print (e)

[[ 5.]
 [ 4.]
 [-3.]]


In [83]:
d = linalg.eig(a) #autovalores, autovectores
print (d)

(array([ 1.,  1.,  1.]), matrix([[  0.00000000e+00,   1.11022302e-16,   1.11022302e-16],
        [  0.00000000e+00,   0.00000000e+00,   2.46519033e-32],
        [  1.00000000e+00,  -1.00000000e+00,  -1.00000000e+00]]))


In [84]:
f = matrix ([[3,-1,1],[0,2,0],[1,-1,3]])
g = linalg.eig(f)
print (g)

(array([ 4.,  2.,  2.]), matrix([[ 0.70710678, -0.70710678,  0.40824829],
        [ 0.        ,  0.        ,  0.81649658],
        [ 0.70710678,  0.70710678,  0.40824829]]))
